export const techStack = [
  { name: "React 18", category: "Frontend", description: "Concurrent rendering and component-based UI architecture", badge: "UI" },
  { name: "TypeScript", category: "Frontend", description: "Full static type safety across 10,000+ lines of code", badge: "Types" },
  { name: "Vite 5", category: "Frontend", description: "Sub-second hot reload and highly optimised production builds", badge: "Build" },
  { name: "Tailwind CSS", category: "Frontend", description: "Utility-first design system — consistent across every screen size", badge: "Style" },
  { name: "Framer Motion", category: "Frontend", description: "Physics-based animations and cinematic page transitions", badge: "Motion" },
  { name: "Zustand", category: "Frontend", description: "Lightweight global state without boilerplate", badge: "State" },
  { name: "React Query", category: "Frontend", description: "Server state management with caching and background refetch", badge: "Data" },
  { name: "React Router v7", category: "Frontend", description: "Client-side routing with protected route guards", badge: "Routing" },
  { name: "Spring Boot 3", category: "Backend", description: "Enterprise-grade Java REST API with full Spring Security", badge: "API" },
  { name: "Java 17", category: "Backend", description: "Long-term support release — stable, fast, production-proven", badge: "Runtime" },
  { name: "Hibernate", category: "Backend", description: "JPA ORM for clean database entity management", badge: "ORM" },
  { name: "WebSocket STOMP", category: "Backend", description: "Real-time bidirectional messaging for DM conversations", badge: "Realtime" },
  { name: "Clerk", category: "Auth", description: "JWT-based authentication with zero-trust security model", badge: "Auth" },
  { name: "Turso", category: "Database", description: "Edge SQLite with global low-latency reads via LibSQL", badge: "DB" },
  { name: "Vercel", category: "Hosting", description: "Edge-deployed frontend with automatic CI/CD from GitHub", badge: "CDN" },
  { name: "Render", category: "Hosting", description: "Auto-scaling cloud platform for Spring Boot backend", badge: "Cloud" },
  { name: "Cloudinary", category: "Hosting", description: "Image upload, transformation and CDN delivery", badge: "Media" },
  { name: "Google Gemini", category: "AI & APIs", description: "Powers Krishi Mitra AI chatbot with contextual farm advice", badge: "AI" },
  { name: "OpenWeather", category: "AI & APIs", description: "Hyper-local meteorological data for all 31 Karnataka districts", badge: "Weather" },
  { name: "Data.gov.in", category: "AI & APIs", description: "Official APMC mandi price data — updated daily by the government", badge: "Market" },
  { name: "Gmail SMTP", category: "AI & APIs", description: "Transactional email for notifications and account actions", badge: "Email" },
];
